### ISSUE TITLE
centos image doesn't have `ip` command?

### ISSUE THREAD

**Issue by dougbtv** [dougbtv/zebra-pen#1]
waaaat? that's a bummer. update image to a different one, or make sure it has ip command installed.

**Comment by s1061123** [comment]
centos seems not to have 'ip' command, so you can install it by 'yum install -y iproute'.

**Comment by dougbtv** [comment]
Thanks for the pointer Tomo, appreciate it! Confused me that the `centos:centos7` base image didn't have `ip`
